name: Java CI with Gradle

on:
  push:
    branches: [ "master", "main" ]
  pull_request:
    branches: [ "master", "main" ]
  workflow_call:  # allow this workflow to be reused by others (like deploy)
  workflow_dispatch:

permissions:
  contents: read

jobs:
  gradle_check:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ '11', '17', '21', '22', '23' ]
    steps:
      - uses: actions/checkout@v4
        with:
          ref: master
          fetch-depth: 0
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java }}
          distribution: 'temurin'
      - name: Build with Gradle
        run: ./gradlew build check shadow
      - name: Upload JAR artifacts
        uses: actions/upload-artifact@65c4c4a1ddee5b72f698fdd19549f0f0fb45cf08 # v4.6.0
        with:
          name: artifacts
          path: build/libs/*.jar


  gradle_publish:
    needs: gradle_check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
        with:
          fetch-depth: 0
      - name: Set up JDK 11
        uses: actions/setup-java@main
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Build with Gradle
        uses: gradle/actions/setup-gradle@main
      - name: Publish with Gradle
        run: ./gradlew publish
        env:
          USERNAME: ${{ github.actor }}
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
