name: Publish with Gradle

on:
  push:
    branches: [ "master", "main" ]

permissions:
  contents: read

jobs:
  build:
    uses: ./.github/workflows/build.yml
  gradle_publish:
    name: Publish package to Maven Central
    needs: [ build ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
        with:
          fetch-depth: 0
      - name: Set up JDK 11
        uses: actions/setup-java@main
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Build with Gradle
        uses: gradle/actions/setup-gradle@main
      - name: Publish with Gradle
        run: ./gradlew publish
        env:
          USERNAME: ${{ github.actor }}
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
